### ISSUE TITLE
Impossible!

### ISSUE THREAD

**Issue by simPod** [hugovk/year-progress-bar#2]
![image](https://user-images.githubusercontent.com/327717/71634583-92652f80-2c1d-11ea-87d5-67a30ddf147f.png)

I'm sorry but I don't think it's real!

**Comment by hugovk** [comment]
Oops! Happy new year anyway!

**Comment by simPod** [comment]
Same to you! 🎉 


┏━━┓┏━━┓┏━━┓┏━━┓
┗━┓┃┃┏┓┃┗━┓┃┃┏┓┃
┏━┛┃┃┃┃┃┏━┛┃┃┃┃┃
‎‎‎‎‎‎‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎long live the float
┃┏━┛┃┃┃┃┃┏━┛┃┃┃┃
┃┗━┓┃┗┛┃┃┗━┓┃┗┛┃
┗━━┛┗━━┛┗━━┛┗━━
